### ISSUE TITLE
editionable keyword missing

### ISSUE THREAD

**Issue by kangel5** [kufii/sublime-sql-formatter#1]
Excellent package, love it!

Issue #1)
When I'm formatting views, I noticed that the keyword:
editionable
Isn't changed to uppercase.

So It looks like:
CREATE OR REPLACE 
FORCE editionable VIEW

Issue #2)
When I format the SQL, it likes to add 2x line returns after a comment:
-- I am a comment

The problem with this is when I run the scripts via sqlplus on cli, the line break is taken as the end of statement, which it's not.  How do I alter that in my user settings to disable this particular feature?

Thank you,

Karl.

**Comment by kufii** [comment]
hey, so the actual formatting is controlled by a 3rd party library, so it would be best to open a ticket there instead:

https://github.com/zeroturnaround/sql-formatter/issues
